// Build -> 3D preview layer stack and labels (WS2c). Pure.
//
// Geometry comes from the render index (one render per shape); prints come
// from `prints` (a vendor photo or a generated texture), applied in the
// browser. So a new dial needs no render: the same surface job, another print.
//
// Every scene carries labels for what isn't the real product (non-negotiable
// "label what isn't real"): which prints are generated, which shapes are
// approximated, and that metal finishes aren't shown.

import type { Layer } from "./compositor";

export interface RenderIndex {
  order: string[];
  pair: { layer: string; replaces: string[]; views: string[] };
  jobs: Record<string, { stem: string; pass: "beauty" | "surface" }>;
  parts: Record<string, { key: string; approximated: boolean; actualShape?: string }>;
  notRenderable: Record<string, string>;
}

export interface Print {
  src: string;
  /** True for a texture Modbench made, not the vendor's photo. Required: an unlabelled print can't be built. */
  generated: boolean;
}

export interface SceneInput {
  index: RenderIndex;
  view: "hero" | "top";
  /** slot -> part id, as in a Build. */
  parts: Partial<Record<string, string>>;
  prints: Partial<Record<"dial" | "date" | "ring" | "insert", Print>>;
}

export type Scene = { ok: true; layers: Layer[]; labels: string[] } | { ok: false; reason: string };

const SLOT_OF_LAYER: Record<string, string> = { dial: "dial", date: "dial", ring: "chapterRing", insert: "bezelInsert", hands: "hands", strap: "strap" };
const NAMES: Record<string, string> = { dial: "Dial", date: "Date wheel", ring: "Chapter ring", insert: "Insert", hands: "Hands", strap: "Strap", crown: "Crown" };

export function resolveScene({ index, view, parts, prints }: SceneInput): Scene {
  const caseId = parts.case;
  if (!caseId) return { ok: false, reason: "no case chosen" };
  const caseEntry = index.parts[caseId];
  if (!caseEntry) return { ok: false, reason: index.notRenderable[caseId] ?? "case not in the render index" };
  const keyOf = (slot: string) => (parts[slot] ? index.parts[parts[slot]!]?.key : undefined);
  const strapKey = keyOf("strap");
  const paired = Boolean(strapKey) && index.pair.views.includes(view);

  const layers: Layer[] = [];
  const labels = ["Shape from the case's stated dimensions"];
  const need = (id: string) => index.jobs[id] ?? null;

  // The case (and the case+strap pair) carry the finish; everything else is
  // keyed by the case's geometry alone.
  const geo = caseEntry.key.split("#")[0]!;
  const caseJob = paired ? need(`${view}/beauty/casestrap/${caseEntry.key}/${strapKey}`) : need(`${view}/beauty/case/${caseEntry.key}`);
  if (!caseJob) return { ok: false, reason: "case not rendered yet" };

  for (const layer of index.order) {
    if (layer === "case") {
      // Rendered with the inner parts held out: seams add, not overlap.
      layers.push({ kind: "beauty", src: `${caseJob.stem}.png`, blend: "disjoint" });
      continue;
    }
    if (layer === "strap" && paired) continue;
    const slot = SLOT_OF_LAYER[layer];
    if (!slot || !parts[slot]) continue;
    const partKey = keyOf(slot);
    if (!partKey) continue; // chosen part isn't renderable: left out, and labelled below
    const job = need(`${view}/${layer === "date" || layer === "dial" || layer === "ring" || layer === "insert" ? "surface" : "beauty"}/${layer}/${geo}/${partKey}`);
    if (!job) return { ok: false, reason: `${layer} not rendered yet` };
    if (job.pass === "surface") {
      const print = prints[layer as keyof SceneInput["prints"]];
      if (!print) {
        if (layer === "dial") return { ok: false, reason: "no dial photo" };
        continue;
      }
      layers.push({ kind: "surface", stem: job.stem, print: print.src });
      labels.push(`${NAMES[layer]}: ${print.generated ? "generic print generated by Modbench, not this part's own design" : "print from vendor photo"}`);
    } else {
      // A separate strap holds out the case; polished hands mix with the dial in linear light.
      const blend = layer === "strap" ? "disjoint" : layer === "hands" ? "linear" : undefined;
      layers.push({ kind: "beauty", src: `${job.stem}.png`, ...(blend ? { blend } : {}) });
    }
  }
  if (paired) labels.push("Strap: shape only, colour not shown");

  for (const [slot, id] of Object.entries(parts)) {
    if (!id) continue;
    const e = index.parts[id];
    const name = NAMES[Object.keys(SLOT_OF_LAYER).find((l) => SLOT_OF_LAYER[l] === slot) ?? slot] ?? slot;
    if (e?.approximated) labels.push(`${name} shape approximated: ${e.actualShape} drawn as ${e.key.split(":")[1]!.split("#")[0]}`);
    // Any chosen part the index doesn't know -- a recorded reason, a part
    // added since the last render run, a submitted (byo_) part -- is left
    // out of the picture, so it must be named. The movement sits hidden.
    if (!e && slot !== "case" && slot !== "movement") labels.push(`${name} not previewed: ${index.notRenderable[id] ?? "not in the render index"}`);
  }
  return { ok: true, layers, labels };
}
